#  apiVersion - Which version of the Kubernetes API you're using to create this object
apiVersion: v1
#  kind - What kind of object you want to create
kind: Pod
# metadata - Data that helps uniquely identify the object, including a name string, UID, and optional namespace
metadata:
  name: lmpolicycaptureservice
# spec - What state you desire for the object
spec:
  containers:
  - name: lmpolicycaptureservice
    image: cuhlbblew/lmpolicyformsource:1.9
    imagePullPolicy: IfNotPresent
    command: [ "/app/startlmpolicyservice.sh"]
    #args: [ "lmpolicyformsource", "127.0.0.1", "8080", "http://127.0.0.1:8081"]
    args: ["$(SERVICE)", "$(HOST)", "$(PORT)", "$(BROKER)", "$(TOPIC)", "$(REG)"]
    env:
    - name:  SERVICE
      value: "lmpolicycaptureservice"
    - name:  HOST
      value: "127.0.0.1"
    - name:  PORT
      value: "8080"
    - name:  BROKER
      value: "PLAINTEXT://kafka.confluent.svc.cluster.local:9071"
    - name:  TOPIC
      value: "policy-protobuf"
    - name:  REG
      value: "http://schemaregistry-0.schemaregistry.confluent.svc.cluster.local:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: lmpolicycaptureservice
spec:
  type: ClusterIP ### may be ommited as it is a default type
  selector:
    name: lmpolicycaptureservice ### should match your labels defined for your backend pods
  ports:
  - protocol: TCP
    targetPort: 8000 ### port your backend app listens on
    port: 8081 ### port on which you want to expose it within your cluster
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lmpolicycaptureservice-ingress
spec:
  rules:
  - host: lmpolicycaptureservice
    http:
      paths:
      - backend:
          serviceName: lmpolicycaptureservice
          servicePort: 8081
        path: /
  tls:
  - hosts:
    - lmpolicycaptureservice
