apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    #Pod templates Controllers for workload resources create Pods from a pod template and manage those Pods on your behalf.
    # This is the pod template
    spec:
      containers:
      - name: hello
        image: busybox
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      restartPolicy: OnFailure
    # The pod template ends here
