apiVersion: batch/v1
kind: Job
metadata:
  name: service
spec:
  template:
    metadata:
      name: service-pod
    spec:
      containers:
      - name: service-world
        image: service
        imagePullPolicy: Never
      restartPolicy: Never
